on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
name: dev-build
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
    - name: Build
      run: make
    - name: Upload Binary
      uses: actions/upload-artifact@v1
      with:
        name: build-${{ matrix.platform }}
        path: ./build/
